#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

export NNN_BMS=".:~/.config;v:~/Videos"
export NNN_COLORS='#0e090a0b;4123'
export NNN_TRASH=1
export NNN_PLUG='p:preview-tui'
export SPLIT='v'
