#! /bin/sh

~/.config/polybar/launch.sh
killall -w dunst picom udiskie nm-applet parcellite cbatticon
dunst &
picom -b
udiskie &
nm-applet &
parcellite &
cbatticon &

xrandr --output LVDS1 --primary --auto --output HDMI1 --auto --right-of LVDS1

bspc monitor LVDS1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6

bspc config border_width          2
bspc config window_gap            0
bspc config focused_border_color "#7b68ee"
bspc config normal_border_color  "#000000"
bspc config active_border_color  "#000000"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
